spring:
  application:
    name: reviews-app

config:
  import: "optional:file:.env[.properties]"

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

app:
  openai:
    base-url: ${OPENAI_BASE_URL}
    model: ${OPENAI_MODEL}
    api-key: ${OPENAI_API_KEY}
    jsonl-chunk-size: ${BATCH_JSONL_CHUNK_SIZE:5}

  batch:
    portion-size: ${BATCH_PORTION_SIZE:5}
    poll-interval-seconds: ${BATCH_POLL_INTERVAL_SECONDS}
    max-retry: ${BATCH_MAX_RETRY}
